export const enum Boss {
  '亜人の女王＆亜人の剣聖' = '亜人の女王＆亜人の剣聖',
  '鈴玉狩り' = '鈴玉狩り',
  '貪食ドラゴン' = '貪食ドラゴン',
  '夜の騎兵' = '夜の騎兵',
  '英雄のガーゴイル' = '英雄のガーゴイル',
  'ミミズ顔' = 'ミミズ顔',
  '公のフレイディア' = '公のフレイディア',
  '百足のデーモン' = '百足のデーモン',
  '熔鉄デーモン' = '熔鉄デーモン',
  '戦場の宿将' = '戦場の宿将',
  'ティビアの呼び舟＆死に生きる者たち' = 'ティビアの呼び舟＆死に生きる者たち',
  '爛れた樹霊' = '爛れた樹霊',
  '接ぎ木の君主' = '接ぎ木の君主',
  '王族の幽鬼' = '王族の幽鬼',

  'ツリーガード＆王都の騎兵' = 'ツリーガード＆王都の騎兵',
  '忌み鬼' = '忌み鬼',
  '古竜' = '古竜',
  '坩堝の騎士＆黄金カバ' = '坩堝の騎士＆黄金カバ',
  '僻地の宿将' = '僻地の宿将',
  'ノクスの竜人兵' = 'ノクスの竜人兵',
  '竜のツリーガード＆王都の騎兵' = '竜のツリーガード＆王都の騎兵',
  '大土竜' = '大土竜',
  '神肌の貴種＆神肌の使徒' = '神肌の貴種＆神肌の使徒',
  '降る星の成獣' = '降る星の成獣',
  '死儀礼の鳥' = '死儀礼の鳥',
  '無名の王' = '無名の王',
  '冷たい谷の踊り子' = '冷たい谷の踊り子',

  'Gladius' = '夜の獣、グラディウス',
  'Adel' = '夜の爵、エデレ',
  'Gnoster' = '夜の識、グノスター',
  'Maris' = '深海の夜、マリス',
  'Libra' = '夜の魔、リブラ',
  'Fulghor' = '夜光の騎士、フルゴール',
  'Caligo' = '夜の霞、カリゴ',
  'Heolstor' = '夜の王、ナメレス',
}

export const day1Bosses: [Boss, ReadonlySet<Boss>][] = [
  [Boss['亜人の女王＆亜人の剣聖'], new Set([Boss.Gladius, Boss.Heolstor])],
  [Boss.鈴玉狩り, new Set([Boss.Gladius, Boss.Heolstor])],
  [Boss.貪食ドラゴン, new Set([Boss.Adel, Boss.Maris, Boss.Fulghor, Boss.Heolstor])],
  [Boss.夜の騎兵, new Set([Boss.Adel, Boss.Fulghor, Boss.Heolstor])],
  [Boss.英雄のガーゴイル, new Set([Boss.Adel, Boss.Maris, Boss.Heolstor])],
  [Boss.ミミズ顔, new Set([Boss.Adel, Boss.Maris, Boss.Fulghor, Boss.Heolstor])],
  [Boss.公のフレイディア, new Set([Boss.Adel, Boss.Libra, Boss.Caligo, Boss.Heolstor])],
  [Boss.百足のデーモン, new Set([Boss.Gnoster, Boss.Libra, Boss.Fulghor, Boss.Heolstor])],
  [Boss.熔鉄デーモン, new Set([Boss.Gnoster, Boss.Maris, Boss.Caligo, Boss.Heolstor])],
  [Boss.戦場の宿将, new Set([Boss.Gnoster, Boss.Libra, Boss.Heolstor])],
  [Boss['ティビアの呼び舟＆死に生きる者たち'], new Set([Boss.Gnoster, Boss.Libra, Boss.Caligo, Boss.Heolstor])],
  [Boss.爛れた樹霊, new Set([Boss.Gnoster, Boss.Caligo, Boss.Heolstor])],
  [Boss.接ぎ木の君主, new Set([Boss.Maris, Boss.Caligo, Boss.Heolstor])],
  [Boss.王族の幽鬼, new Set([Boss.Libra, Boss.Fulghor, Boss.Heolstor])],
]

export const day2Bosses: [Boss, ReadonlySet<Boss>][] = [
  [Boss['ツリーガード＆王都の騎兵'], new Set([Boss.Gladius, Boss.Maris, Boss.Heolstor])],
  [Boss.忌み鬼, new Set([Boss.Gladius, Boss.Heolstor])],
  [Boss.古竜, new Set([Boss.Adel, Boss.Heolstor])],
  [Boss['坩堝の騎士＆黄金カバ'], new Set([Boss.Adel, Boss.Libra, Boss.Heolstor])],
  [Boss.僻地の宿将, new Set([Boss.Adel, Boss.Fulghor, Boss.Heolstor])],
  [Boss.ノクスの竜人兵, new Set([Boss.Gnoster, Boss.Fulghor, Boss.Heolstor])],
  [Boss['竜のツリーガード＆王都の騎兵'], new Set([Boss.Gnoster, Boss.Caligo, Boss.Heolstor])],
  [Boss.大土竜, new Set([Boss.Gnoster, Boss.Heolstor])],
  [Boss['神肌の貴種＆神肌の使徒'], new Set([Boss.Maris, Boss.Libra, Boss.Caligo, Boss.Heolstor])],
  [Boss.降る星の成獣, new Set([Boss.Maris, Boss.Heolstor])],
  [Boss.死儀礼の鳥, new Set([Boss.Libra, Boss.Heolstor])],
  [Boss.無名の王, new Set([Boss.Fulghor, Boss.Heolstor])],
  [Boss.冷たい谷の踊り子, new Set([Boss.Caligo, Boss.Heolstor])],
]

export const events: [string, ReadonlySet<Boss>][] = [
  ['夜の勢力', new Set([Boss.Gladius, Boss.Maris, Boss.Fulghor])],
  ['隕石', new Set([Boss.Gladius, Boss.Adel, Boss.Caligo])],
  ['新たなる脅威', new Set([Boss.Adel, Boss.Fulghor])],
  ['狂い火', new Set([Boss.Gnoster, Boss.Libra])],
  ['古の魔術師塔', new Set([Boss.Gnoster, Boss.Libra])],
  ['歩く霊廟', new Set([Boss.Maris, Boss.Caligo])],
  ['忌み鬼', new Set([Boss.Adel, Boss.Gnoster, Boss.Heolstor])],
  ['兆し', new Set([Boss.Gnoster, Boss.Caligo, Boss.Heolstor])],
  ['知性の蟲', new Set([Boss.Maris, Boss.Libra, Boss.Heolstor])],
  ['調律の魔物', new Set([Boss.Fulghor, Boss.Caligo, Boss.Heolstor])],
]

export const enum Effects {
  '◎' = '◎',
  '◯' = '◯',
  '－' = '－',
  '△' = '△',
  '✕' = '✕',
}

export const bossTable: Record<Boss, Record<
  '魔'
  | '炎'
  | '雷'
  | '聖'
  | '血'
  | '毒'
  | '腐'
  | '冷'
  | '眠',
  Effects | Effects[]>> = {
  [Boss['亜人の女王＆亜人の剣聖']]: {
    魔: Effects['－'],
    炎: Effects['◯'],
    雷: Effects['－'],
    聖: Effects['－'],
    血: Effects['◎'],
    毒: Effects['◎'],
    腐: Effects['◎'],
    冷: Effects['◎'],
    眠: Effects['◎'],
  },
  [Boss.鈴玉狩り]: {
    魔: Effects['✕'],
    炎: Effects['✕'],
    雷: Effects['△'],
    聖: Effects['✕'],
    血: Effects['◯'],
    毒: Effects['◎'],
    腐: Effects['◎'],
    冷: Effects['◯'],
    眠: Effects['◎'],
  },
  [Boss.貪食ドラゴン]: {
    魔: Effects['◯'],
    炎: Effects['◯'],
    雷: Effects['◯'],
    聖: Effects['◯'],
    血: Effects['◎'],
    毒: Effects['✕'],
    腐: Effects['✕'],
    冷: Effects['◎'],
    眠: Effects['✕'],
  },
  [Boss.夜の騎兵]: {
    魔: Effects['✕'],
    炎: Effects['✕'],
    雷: Effects['△'],
    聖: Effects['✕'],
    血: Effects['◯'],
    毒: Effects['◎'],
    腐: Effects['◎'],
    冷: Effects['◯'],
    眠: Effects['✕'],
  },
  [Boss.英雄のガーゴイル]: {
    魔: Effects['△'],
    炎: Effects['✕'],
    雷: Effects['✕'],
    聖: Effects['✕'],
    血: Effects['✕'],
    毒: Effects['✕'],
    腐: Effects['✕'],
    冷: Effects['✕'],
    眠: Effects['✕'],
  },
  [Boss.ミミズ顔]: {
    魔: Effects['－'],
    炎: Effects['－'],
    雷: Effects['－'],
    聖: Effects['✕'],
    血: Effects['◯'],
    毒: Effects['△'],
    腐: Effects['◯'],
    冷: Effects['◯'],
    眠: Effects['◯'],
  },
  [Boss.公のフレイディア]: {
    魔: Effects['✕'],
    炎: Effects['△'],
    雷: Effects['✕'],
    聖: Effects['✕'],
    血: Effects['◯'],
    毒: Effects['✕'],
    腐: Effects['◯'],
    冷: Effects['◯'],
    眠: Effects['✕'],
  },
  [Boss.百足のデーモン]: {
    魔: Effects['◯'],
    炎: Effects['✕'],
    雷: Effects['◯'],
    聖: Effects['◯'],
    血: Effects['◯'],
    毒: Effects['◯'],
    腐: Effects['◯'],
    冷: Effects['◯'],
    眠: Effects['✕'],
  },
  [Boss.熔鉄デーモン]: {
    魔: Effects['△'],
    炎: Effects['✕'],
    雷: Effects['△'],
    聖: Effects['△'],
    血: Effects['✕'],
    毒: Effects['◎'],
    腐: Effects['◎'],
    冷: Effects['◯'],
    眠: Effects['✕'],
  },
  [Boss.戦場の宿将]: {
    魔: Effects['△'],
    炎: Effects['△'],
    雷: Effects['△'],
    聖: Effects['△'],
    血: Effects['◎'],
    毒: Effects['◎'],
    腐: Effects['◎'],
    冷: Effects['◎'],
    眠: Effects['◎'],
  },
  [Boss['ティビアの呼び舟＆死に生きる者たち']]: {
    魔: Effects['△'],
    炎: Effects['△'],
    雷: Effects['✕'],
    聖: Effects['◎'],
    血: Effects['✕'],
    毒: Effects['✕'],
    腐: Effects['◎'],
    冷: Effects['✕'],
    眠: Effects['✕'],
  },
  [Boss.爛れた樹霊]: {
    魔: Effects['△'],
    炎: Effects['◯'],
    雷: Effects['△'],
    聖: Effects['✕'],
    血: Effects['◯'],
    毒: Effects['◯'],
    腐: Effects['◯'],
    冷: Effects['◯'],
    眠: Effects['✕'],
  },
  [Boss.接ぎ木の君主]: {
    魔: Effects['△'],
    炎: Effects['△'],
    雷: Effects['△'],
    聖: Effects['✕'],
    血: Effects['◎'],
    毒: Effects['◎'],
    腐: Effects['◎'],
    冷: Effects['◎'],
    眠: Effects['◎'],
  },
  [Boss.王族の幽鬼]: {
    魔: Effects['－'],
    炎: Effects['－'],
    雷: Effects['－'],
    聖: Effects['✕'],
    血: Effects['◎'],
    毒: Effects['◎'],
    腐: Effects['◎'],
    冷: Effects['◎'],
    眠: Effects['✕'],
  },

  [Boss['ツリーガード＆王都の騎兵']]: {
    魔: Effects['△'],
    炎: Effects['✕'],
    雷: Effects['－'],
    聖: Effects['△'],
    血: Effects['◯'],
    毒: Effects['◎'],
    腐: Effects['◎'],
    冷: Effects['◯'],
    眠: Effects['◎'],
  },
  [Boss.忌み鬼]: {
    魔: Effects['－'],
    炎: Effects['－'],
    雷: Effects['－'],
    聖: Effects['✕'],
    血: Effects['◎'],
    毒: Effects['◎'],
    腐: Effects['◎'],
    冷: Effects['◎'],
    眠: Effects['◯'],
  },
  [Boss.古竜]: {
    魔: Effects['✕'],
    炎: Effects['✕'],
    雷: Effects['✕'],
    聖: Effects['✕'],
    血: Effects['◯'],
    毒: Effects['◯'],
    腐: Effects['◯'],
    冷: Effects['◯'],
    眠: Effects['✕'],
  },
  [Boss['坩堝の騎士＆黄金カバ']]: {
    魔: [Effects['✕'], Effects['－']],
    炎: [Effects['△'], Effects['◯']],
    雷: [Effects['△'], Effects['◯']],
    聖: [Effects['✕'], Effects['－']],
    血: [Effects['✕'], Effects['◯']],
    毒: [Effects['◯'], Effects['◎']],
    腐: [Effects['◯'], Effects['◎']],
    冷: [Effects['◯'], Effects['◯']],
    眠: [Effects['◯'], Effects['✕']],
  },
  [Boss.僻地の宿将]: {
    魔: Effects['△'],
    炎: Effects['△'],
    雷: Effects['△'],
    聖: Effects['△'],
    血: Effects['◎'],
    毒: Effects['◎'],
    腐: Effects['◎'],
    冷: Effects['◎'],
    眠: Effects['◎'],
  },
  [Boss.ノクスの竜人兵]: {
    魔: Effects['△'],
    炎: Effects['△'],
    雷: Effects['✕'],
    聖: Effects['△'],
    血: Effects['◯'],
    毒: Effects['◯'],
    腐: Effects['◯'],
    冷: Effects['△'],
    眠: Effects['✕'],
  },
  [Boss['竜のツリーガード＆王都の騎兵']]: {
    魔: Effects['△'],
    炎: Effects['✕'],
    雷: Effects['✕'],
    聖: Effects['△'],
    血: Effects['◯'],
    毒: Effects['◎'],
    腐: Effects['◎'],
    冷: Effects['◯'],
    眠: Effects['◎'],
  },
  [Boss.大土竜]: {
    魔: Effects['✕'],
    炎: Effects['✕'],
    雷: Effects['✕'],
    聖: Effects['✕'],
    血: Effects['◯'],
    毒: Effects['◯'],
    腐: Effects['◯'],
    冷: Effects['△'],
    眠: Effects['◎'],
  },
  [Boss['神肌の貴種＆神肌の使徒']]: {
    魔: Effects['△'],
    炎: Effects['✕'],
    雷: Effects['△'],
    聖: Effects['✕'],
    血: Effects['◯'],
    毒: Effects['◎'],
    腐: Effects['◎'],
    冷: Effects['◎'],
    眠: Effects['◎'],
  },
  [Boss.降る星の成獣]: {
    魔: Effects['△'],
    炎: Effects['△'],
    雷: Effects['△'],
    聖: Effects['△'],
    血: Effects['◯'],
    毒: Effects['◯'],
    腐: Effects['◯'],
    冷: Effects['✕'],
    眠: Effects['✕'],
  },
  [Boss.死儀礼の鳥]: {
    魔: Effects['△'],
    炎: Effects['△'],
    雷: Effects['✕'],
    聖: Effects['◎'],
    血: Effects['✕'],
    毒: Effects['✕'],
    腐: Effects['◯'],
    冷: Effects['✕'],
    眠: Effects['✕'],
  },
  [Boss.無名の王]: {
    魔: [Effects['－'], Effects['△']],
    炎: [Effects['△'], Effects['△']],
    雷: [Effects['◯'], Effects['✕']],
    聖: [Effects['－'], Effects['－']],
    血: [Effects['◯'], Effects['◯']],
    毒: [Effects['◯'], Effects['✕']],
    腐: [Effects['◯'], Effects['◯']],
    冷: [Effects['◎'], Effects['◯']],
    眠: [Effects['✕'], Effects['✕']],
  },
  [Boss.冷たい谷の踊り子]: {
    魔: Effects['△'],
    炎: Effects['△'],
    雷: Effects['△'],
    聖: Effects['◯'],
    血: Effects['◯'],
    毒: Effects['✕'],
    腐: Effects['◯'],
    冷: Effects['✕'],
    眠: Effects['✕'],
  },
  [Boss.Gladius]: {
    魔: Effects['－'],
    炎: Effects['✕'],
    雷: Effects['－'],
    聖: Effects['◎'],
    血: Effects['◯'],
    毒: Effects['△'],
    腐: Effects['◯'],
    冷: Effects['△'],
    眠: Effects['◎'],
  },
  [Boss.Adel]: {
    魔: Effects['－'],
    炎: Effects['△'],
    雷: Effects['✕'],
    聖: Effects['－'],
    血: Effects['△'],
    毒: Effects['◎'],
    腐: Effects['◎'],
    冷: Effects['◎'],
    眠: Effects['◎'],
  },
  [Boss.Gnoster]: {
    魔: [Effects['✕'], Effects['－']],
    炎: [Effects['◎'], Effects['◎']],
    雷: [Effects['－'], Effects['－']],
    聖: [Effects['－'], Effects['－']],
    血: [Effects['◎'], Effects['◎']],
    毒: [Effects['△'], Effects['◯']],
    腐: [Effects['◎'], Effects['◎']],
    冷: [Effects['◎'], Effects['◎']],
    眠: [Effects['△'], Effects['◎']],
  },
  [Boss.Maris]: {
    魔: Effects['△'],
    炎: Effects['✕'],
    雷: Effects['◎'],
    聖: Effects['△'],
    血: Effects['✕'],
    毒: Effects['✕'],
    腐: Effects['◯'],
    冷: Effects['◯'],
    眠: Effects['✕'],
  },
  [Boss.Libra]: {
    魔: Effects['△'],
    炎: Effects['◯'],
    雷: Effects['－'],
    聖: Effects['◎'],
    血: Effects['◯'],
    毒: Effects['◎'],
    腐: Effects['◎'],
    冷: Effects['◯'],
    眠: Effects['✕'],
  },
  [Boss.Fulghor]: {
    魔: Effects['－'],
    炎: Effects['－'],
    雷: Effects['◯'],
    聖: Effects['△'],
    血: Effects['◎'],
    毒: Effects['◎'],
    腐: Effects['◎'],
    冷: Effects['◎'],
    眠: Effects['◎'],
  },
  [Boss.Caligo]: {
    魔: Effects['△'],
    炎: Effects['◎'],
    雷: Effects['△'],
    聖: Effects['△'],
    血: Effects['◯'],
    毒: Effects['◯'],
    腐: Effects['◯'],
    冷: Effects['△'],
    眠: Effects['△'],
  },
  [Boss.Heolstor]: {
    魔: [Effects['－'], Effects['－']],
    炎: [Effects['◯'], Effects['－']],
    雷: [Effects['－'], Effects['◯']],
    聖: [Effects['◎'], Effects['◯']],
    血: Effects['✕'],
    毒: Effects['✕'],
    腐: Effects['◯'],
    冷: Effects['✕'],
    眠: Effects['△'],
  },
}
